name: MERN Auto-Deployment

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install and Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
        env:
          VITE_DOMAIN_NAME: http://${{ secrets.DOMAIN_NAME }}:5001

      - name: Install Backend & Setup Environment
        working-directory: ./backend
        run: |
          npm install
          touch .env
          echo "MONGO_URI"=${{ secrets.MONGO_URI }} > .env
          echo "JWT_SECRET"=${{ secrets.JWT_SECRET }} >> .env
          echo "PORT"=${{ secrets.PORT }} >> .env

      - name: Deploy to Live Server
        run: |
          pm2 restart all
          pm2 save
