name: MERN Auto-Deployment

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - runner: prod-1
            domain_secret_name: DOMAIN_NAME_PROD_1
          - runner: prod-2
            domain_secret_name: DOMAIN_NAME_PROD_2

    name: Build and Deploy (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install and Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          echo "REACT_APP_DOMAIN_NAME=http://${{ secrets.REACT_APP_DOMAIN_NAME }}" > .env
          npm run build

      - name: Install Backend & Setup Environment
        working-directory: ./backend
        run: |
          npm install
          touch .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

      - name: Deploy to Live Server
        run: |
          pm2 restart all
          pm2 save
