name: Manual Domain Update

on:
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  update-domain:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Rebuild Frontend with New Secret
        working-directory: ./frontend
        run: |
          npm install
          npm run build
        env:
          REACT_APP_DOMAIN_NAME: http://${{ secrets.DOMAIN_NAME }}:5001

      - name: Refresh PM2
        run: |
          pm2 restart all
          pm2 save
